export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const ACTION_LOGIN_ERROR = 'ACTION_LOGIN_ERROR';


export const GET_UNITS = 'GET_UNITS';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';
export const GET_UNITS_ERROR = 'GET_UNITS_ERROR';

export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
export const GET_MEASUREMENTS_SUCCESS='GET_MEASUREMENTS_SUCCESS';
export const GET_MEASUREMENTS_ERROR = 'GET_MEASUREMENTS_ERROR';
